name: LemonSqueezerPaper
version: '${version}'
main: org.empirewar.lemonsqueezer.LemonSqueezerPaper
api-version: 1.20
description: Lemons for all!
website: https://www.empirewar.org
depend: ["LemonadeStand"]
